export const WORKOUTGROUPS_LOADING = 'WORKOUTGROUPS_LOADING';
export const ADD_WORKOUTGROUPS = 'ADD_WORKOUTGROUPS';
export const WORKOUTGROUPS_FAILED = 'WORKOUTGROUPS_FAILED';

export const ADD_EXERCISES = 'ADD_EXERCISES';
export const EXERCISES_FAILED = 'EXERCISES_FAILED';

export const ADD_LOGS = 'ADD_LOGS';
export const LOGS_FAILED = 'LOGS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const TRAINERS_LOADING = 'TRAINERS_LOADING';
export const ADD_TRAINERS = 'ADD_TRAINERS';
export const TRAINERS_FAILED = 'TRAINERS_FAILED';

// TODO
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_COMMENT = 'ADD_COMMENT';